on:
  workflow_dispatch:
  pull_request:

jobs:
  ecosystem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust toolchain"
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all
      
      - uses: actions/checkout@v3
        with:
          name: zulip/zulip
          ref: refs/heads/main
          path: ecosystem/zulip
      - run: cargo run -- check --config ecosystem/zulip/pyproject.toml ecosystem/zulip
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
