on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: 1
          message: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          comment_tag: ecosystem-results