on:
  workflow_run:
    workflows: [ci]
    types: [completed]

jobs:
  ecosystem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install Rust toolchain"
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --all
