on:
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          name: ecosystem-result
          branch: ${{ github.event.pull_request.head.ref }}
          check_artifacts: true
      - name: Create comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{ github }}
          message: |
            ecosystem check!
          comment_tag: ecosystem-results